typography_spectrum: 0.5925333278719336
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.42223250051029027
  lightness: 0.8969348545651883
  saturation: 0.7077988525852561
  rhythmicContrast: 0.7759877492208034
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7123364561703056
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Patrick Jarrett
  email: contact@jarrettfirm.com
name: Attorney Patrick Jarrett
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4bb24402-de5b-4090-8312-b45c39c6f159.jpg
title: Injury & Immigration Attorney
description: Family-based and Business-based Immigration
purpose: []
